# Generated by Django 6.0.2 on 2026-02-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_reorder_point_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
